from __future__ import annotations

import re
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WEBUI_HTML = REPO_ROOT / "webui" / "index.html"


class WebUIInventoryRegistryHostsTests(unittest.TestCase):
    def test_inventory_panel_exposes_registry_and_host_metadata_strings(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_summary_registry_hosts", html)
        self.assertIn("inventory_summary_provenance", html)
        self.assertIn("inventory_skill_meta_locator", html)
        self.assertIn("inventory_skill_meta_policy", html)
        self.assertIn("inventory_skill_meta_managed_by", html)
        self.assertIn("inventory_meta_host_paths", html)
        self.assertIn("inventory_meta_source_supports", html)

    def test_inventory_panel_scripts_render_registry_kind_and_host_supports(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("function inventorySourceKindLabel(item)", html)
        self.assertIn("supports_source_kinds", html)
        self.assertIn("target_paths", html)
        self.assertIn("inventory_summary_registry_hosts", html)
        self.assertIn("source_provenance_resolved_total", html)
        self.assertIn("source_provenance_unresolved_total", html)
        self.assertIn("inventory_summary_install_atom", html)

    def test_inventory_panel_exposes_install_atom_evidence_helpers(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_improve_all_skills", html)
        self.assertIn("inventory_improve_all_skills_running", html)
        self.assertIn("inventory_improve_all_skills_confirm", html)
        self.assertIn("inventory_improve_all_skills_success", html)
        self.assertIn("inventory_skill_meta_evidence", html)
        self.assertIn("inventory_skill_meta_resolution", html)
        self.assertIn("inventory_skill_meta_resolver", html)
        self.assertIn("inventory_skill_meta_atom_changed", html)
        self.assertIn("inventory_install_atom_title", html)
        self.assertIn("inventory_install_atom_summary", html)
        self.assertIn("inventory_install_atom_filter_label", html)
        self.assertIn("inventory_install_atom_strategy_label", html)
        self.assertIn("inventory_install_atom_strategy_high_confidence", html)
        self.assertIn("inventory_install_atom_refresh_unresolved", html)
        self.assertIn("inventory_install_atom_refresh_done_rich", html)
        self.assertIn("inventory_install_atom_retry_failed", html)
        self.assertIn("inventory_install_atom_retry_noop", html)
        self.assertIn("inventory_install_atom_refresh_report_title", html)
        self.assertIn("inventory_install_atom_refresh_report_group", html)
        self.assertIn("inventory_install_atom_refresh_report_nochange", html)
        self.assertIn("inventory_install_atom_non_actionable_root_only", html)
        self.assertIn("inventory_aggregation_badge_root_only", html)
        self.assertIn('id="inventoryInstallAtomSummary"', html)
        self.assertIn('id="inventoryInstallAtomRows"', html)
        self.assertIn('id="inventoryInstallAtomFilterTabs"', html)
        self.assertIn('id="inventoryInstallAtomRefreshStrategyTabs"', html)
        self.assertIn('id="inventoryInstallAtomRefreshReport"', html)
        self.assertIn('id="inventoryRefreshUnresolvedAtomsBtn"', html)
        self.assertIn('id="inventoryRetryFailedAtomsBtn"', html)
        self.assertIn("inventoryInstallAtomSummary", html)
        self.assertIn("inventoryInstallAtomRows", html)
        self.assertIn("function inventoryAggregationEvidenceSummary(", html)
        self.assertIn("function inventoryInstallAtomRegistrySnapshot(", html)
        self.assertIn("function inventoryPrimarySourceKeyByInstallUnitId(", html)
        self.assertIn("focusInventorySourceByInstallUnit(", html)
        self.assertIn("function normalizeInventoryInstallAtomFilter(", html)
        self.assertIn("function normalizeInventoryInstallAtomRefreshStrategy(", html)
        self.assertIn("syncInventoryInstallAtomFilterTabs(", html)
        self.assertIn("syncInventoryInstallAtomRefreshStrategyTabs(", html)
        self.assertIn("function inventoryInstallAtomRefreshCandidates(", html)
        self.assertIn("function inventoryFailedInstallUnitIdsFromRefreshReport(", html)
        self.assertIn("function inventoryInstallAtomIsActionable(", html)
        self.assertIn("function inventoryInstallAtomActionHint(", html)
        self.assertIn("function inventoryInstallAtomResolutionRank(", html)
        self.assertIn("function inventoryInstallAtomEvidenceRank(", html)
        self.assertIn("function inventoryInstallAtomRowByInstallUnitId(", html)
        self.assertIn("function inventoryInstallAtomRefreshImproved(", html)
        self.assertIn("runInstallAtomAggregateRefresh(", html)
        self.assertIn("retryFailedInstallAtomAggregates(", html)
        self.assertIn("refreshUnresolvedInstallAtomAggregates(", html)
        self.assertIn("improveAllSkills()", html)
        self.assertIn("unresolvedInstallAtomUnitIds(", html)
        self.assertIn("inventoryInstallAtomRefreshReportRows", html)
        self.assertIn("data-inventory-atom-install-unit-id", html)
        self.assertIn("data-inventory-atom-report-install-unit-id", html)
        self.assertIn("inventoryInstallAtomRows\").addEventListener(\"click", html)
        self.assertIn("inventoryInstallAtomRefreshReportRows\").addEventListener(\"click", html)
        self.assertIn("inventoryInstallAtomFilterTabs\").addEventListener(\"click", html)
        self.assertIn("inventoryInstallAtomRefreshStrategyTabs\").addEventListener(\"click", html)
        self.assertIn("inventoryRefreshUnresolvedAtomsBtn\").addEventListener(\"click", html)
        self.assertIn("inventoryRetryFailedAtomsBtn\").addEventListener(\"click", html)
        self.assertIn("/api/skills/install-atoms", html)
        self.assertIn("function inventoryAggregationResolutionLabel(", html)
        self.assertIn("renderInventoryAggregationEvidenceBadge(", html)

    def test_inventory_panel_exposes_provenance_labels_and_helpers(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_skill_meta_provenance", html)
        self.assertIn("inventory_skill_meta_origin", html)
        self.assertIn("inventory_skill_meta_package", html)
        self.assertIn("inventory_skill_meta_confidence", html)
        self.assertIn("inventory_provenance_resolved", html)
        self.assertIn("inventory_provenance_unresolved", html)
        self.assertIn("inventory_provenance_partial", html)
        self.assertIn("inventory_provenance_legacy_note", html)
        self.assertIn("inventory_target_section_provenance", html)
        self.assertIn("inventory_target_section_update_mechanism", html)
        self.assertIn("inventory_target_section_deploy_notes", html)
        self.assertIn("function inventorySourceProvenanceSummary(", html)
        self.assertIn("function inventorySourceProvenanceStateLabel(", html)

    def test_inventory_panel_exposes_manual_source_boundary_labels(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_skill_meta_subpaths", html)
        self.assertIn("inventory_aggregate_kind_source_repo", html)
        self.assertIn("inventory_aggregate_kind_source_root", html)
        self.assertIn("function inventorySourceSubpathSummary(", html)
        self.assertIn("inventory_boundary_title", html)
        self.assertIn("inventory_boundary_collection", html)
        self.assertIn("inventory_boundary_install_unit", html)
        self.assertIn("inventory_boundary_fanout", html)
        self.assertIn("inventory_boundary_subpaths", html)
        self.assertIn("function inventoryBoundaryNotes(", html)

    def test_inventory_panel_exposes_collection_group_fanout_action_note(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("fan out", html)
        self.assertIn("扇出", html)
        self.assertIn("subpathCount", html)

    def test_inventory_panel_exposes_update_all_failure_taxonomy_strings(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_aggregate_update_all_failure_reasons", html)
        self.assertIn("inventory_aggregate_update_all_blocked_reasons", html)
        self.assertIn("inventory_aggregate_update_all_source_sync_cache_hits", html)
        self.assertIn("failed_install_unit_reason_groups", html)
        self.assertIn("blocked_reason_groups", html)
        self.assertIn("source_sync_cache_hit_total", html)

    def test_inventory_panel_exposes_primary_command_rail_and_progress(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryCommandTitle"', html)
        self.assertIn('id="inventoryCommandNote"', html)
        self.assertIn('id="inventoryUpdateAllAggregatesPrimaryBtn"', html)
        self.assertIn('id="inventoryAggregateProgress"', html)
        self.assertIn('id="inventoryAggregateProgressTitle"', html)
        self.assertIn('id="inventoryAggregateProgressNote"', html)
        self.assertIn('id="inventoryAggregateProgressMeta"', html)
        self.assertIn("inventory_command_title", html)
        self.assertIn("inventory_command_note", html)
        self.assertIn("inventory_aggregate_progress_title", html)
        self.assertIn("inventory_aggregate_progress_note", html)
        self.assertIn("inventory_aggregate_progress_meta", html)
        self.assertIn("inventory_aggregate_progress_phase_planning", html)
        self.assertIn("inventory_aggregate_progress_phase_executing", html)
        self.assertIn("inventory_aggregate_progress_phase_executing_command", html)
        self.assertIn("inventory_aggregate_progress_phase_executing_source_sync", html)
        self.assertIn("inventory_aggregate_progress_phase_refreshing", html)
        self.assertIn("inventory_aggregate_progress_phase_refreshing_snapshot", html)
        self.assertIn("inventory_aggregate_progress_phase_done", html)
        self.assertIn("inventory_aggregate_progress_phase_failed", html)
        self.assertIn("inventory_aggregate_progress_meta_runtime", html)
        self.assertIn("inventory-command-deck", html)
        self.assertIn("inventory-command-bar", html)
        self.assertIn("inventory-aggregate-progress-track", html)
        self.assertIn('id="inventoryAggregateProgressFill"', html)
        self.assertIn('id="inventoryAggregateProgressBadge"', html)
        self.assertIn("inventory-progress-slide", html)
        self.assertIn("/api/skills/aggregates/update-all/progress", html)
        self.assertIn("function inventoryAggregateProgressIsActiveStatus(", html)
        self.assertIn("function normalizeInventoryAggregateProgress(", html)
        self.assertIn("function applyInventoryAggregateProgressSnapshot(", html)
        self.assertIn("function loadInventoryAggregateProgress(", html)
        self.assertIn("function inventoryAggregateProgressPhaseLabel(", html)
        self.assertIn("function beginInventoryAggregateProgress(", html)
        self.assertIn("function setInventoryAggregateProgressPhase(", html)
        self.assertIn("function finishInventoryAggregateProgress(", html)

    def test_inventory_panel_exposes_neo_lifecycle_actions_in_source_detail(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_neo_actions_title", html)
        self.assertIn("inventory_neo_sync_action", html)
        self.assertIn("inventory_neo_promote_action", html)
        self.assertIn("inventory_neo_rollback_action", html)
        self.assertIn("function inventoryNeoDetailState(", html)
        self.assertIn("function promoteInventoryNeoSource(", html)
        self.assertIn("function rollbackInventoryNeoSource(", html)
        self.assertIn("data-inventory-neo-action", html)
        self.assertIn("inventorySourceHero\").addEventListener(\"click", html)
        self.assertIn("/api/skills/astrbot-neo-sources/${encodeURIComponent(normalizedSourceId)}/promote", html)
        self.assertIn("/api/skills/astrbot-neo-sources/${encodeURIComponent(normalizedSourceId)}/rollback", html)

    def test_inventory_display_settings_live_in_utility_panel(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryUtilityDrawersTitle"', html)
        self.assertIn('id="inventoryUtilityDrawersNote"', html)
        self.assertIn('id="inventoryUtilitySettingsTitle"', html)
        self.assertIn('id="inventoryUtilitySettingsNote"', html)
        self.assertIn('id="inventoryUtilitySummaryTitle"', html)
        self.assertIn('id="inventoryUtilitySummaryNote"', html)
        self.assertIn('id="inventoryUtilitySummary"', html)
        self.assertIn('id="inventoryUtilityHealthTitle"', html)
        self.assertIn("inventory_utility_drawers_title", html)
        self.assertIn("inventory_utility_drawers_note", html)
        self.assertIn("inventory_utility_settings_title", html)
        self.assertIn("inventory_utility_settings_note", html)
        self.assertIn("inventory_utility_summary_title", html)
        self.assertIn("inventory_utility_summary_note", html)
        self.assertIn("inventory_utility_health_title", html)
        self.assertLess(
            html.index('id="inventoryInspectorUtilityPanel"'),
            html.index('id="inventoryDisplaySettings"'),
        )
        self.assertRegex(
            html,
            re.compile(r'id="inventoryInspectorUtilityPanel".*id="inventoryDisplaySettings"', re.S),
        )

    def test_inventory_utility_panel_groups_low_frequency_areas_into_collapsible_sections(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryUtilityHealthSection"', html)
        self.assertIn('id="inventoryUtilityHealthSummary"', html)
        self.assertIn('id="inventoryUtilityHistorySection"', html)
        self.assertIn('id="inventoryUtilityHistorySummary"', html)
        self.assertIn('id="inventoryUtilityInstallAtomSection"', html)
        self.assertIn('id="inventoryUtilityInstallAtomSectionSummary"', html)
        self.assertIn('id="inventoryUtilityAstrbotSection"', html)
        self.assertIn('id="inventoryUtilityAstrbotSummary"', html)
        self.assertLess(
            html.index('id="inventoryUtilityHistorySection"'),
            html.index('id="inventoryAggregateUpdateReportRows"'),
        )
        self.assertLess(
            html.index('id="inventoryUtilityInstallAtomSection"'),
            html.index('id="inventoryInstallAtomRows"'),
        )
        self.assertLess(
            html.index('id="inventoryUtilityAstrbotSection"'),
            html.index('id="inventoryAstrbotRuntimeSummary"'),
        )

    def test_inventory_panel_uses_compact_main_summary_and_full_utility_summary(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_summary_compact_scope", html)
        self.assertIn("inventory_summary_compact_software", html)
        self.assertIn("inventory_summary_compact_sources", html)
        self.assertIn("inventory_summary_compact_aggregates", html)
        self.assertIn("inventory_summary_compact_freshness", html)
        self.assertIn("inventory_summary_compact_alerts", html)
        self.assertIn("inventory_summary_compact_hidden", html)
        self.assertIn('const utilitySummaryEl = $("inventoryUtilitySummary");', html)
        self.assertIn('const utilitySummaryKpisEl = $("inventoryUtilitySummaryKpis");', html)
        self.assertIn('summaryEl.textContent = compactSummaryParts.join(" · ");', html)
        self.assertIn("setInventorySummaryText(utilitySummaryEl, detailedSummary);", html)
        self.assertIn("inventory_runtime_kpi_scope", html)
        self.assertIn('summaryEl.title = detailedSummary;', html)

    def test_inventory_improve_all_skills_exposes_continuous_progress_contract(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_improve_all_skills_progress_title", html)
        self.assertIn("inventory_improve_all_skills_progress_note_atoms", html)
        self.assertIn("inventory_improve_all_skills_progress_note_aggregates", html)
        self.assertIn("inventory_improve_all_skills_progress_meta_atoms", html)
        self.assertIn("inventory_aggregate_progress_phase_improving_atoms_planning", html)
        self.assertIn("inventory_aggregate_progress_phase_improving_atoms_refreshing", html)
        self.assertIn("inventoryAggregateProgressAtomImprovedCount", html)
        self.assertIn("inventoryAggregateProgressAtomUnchangedCount", html)
        self.assertIn("inventoryAggregateProgressWorkflowKind", html)
        self.assertIn("function inventoryAggregateProgressIsImprovePhase(", html)
        self.assertIn("function beginInventoryImproveSkillsAtomProgress(", html)
        self.assertIn("function updateInventoryImproveSkillsAtomProgress(", html)
        self.assertIn("/api/skills/improve-all", html)

    def test_inventory_panel_exposes_aggregate_update_report_hooks(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryAggregateUpdateReport"', html)
        self.assertIn('id="inventoryAggregateUpdateReportTitle"', html)
        self.assertIn('id="inventoryAggregateUpdateReportNote"', html)
        self.assertIn('id="inventoryAggregateUpdateReportRows"', html)
        self.assertIn('id="inventoryExecutionHistoryModeLabel"', html)
        self.assertIn('id="inventoryExecutionHistoryTabs"', html)
        self.assertIn('id="inventoryExecutionHistoryBatch"', html)
        self.assertIn('id="inventoryExecutionHistoryCurrent"', html)
        self.assertIn('id="inventoryExecutionHistoryRollback"', html)
        self.assertIn('data-inventory-history="batch"', html)
        self.assertIn('data-inventory-history="current"', html)
        self.assertIn('data-inventory-history="rollback"', html)
        self.assertIn("inventory_execution_history_title", html)
        self.assertIn("inventory_execution_history_mode_label", html)
        self.assertIn("inventory_execution_history_batch", html)
        self.assertIn("inventory_execution_history_current", html)
        self.assertIn("inventory_execution_history_rollback", html)
        self.assertIn("inventory_execution_history_waiting", html)
        self.assertIn("inventory_execution_history_empty", html)
        self.assertIn("inventory_execution_history_current_scope", html)
        self.assertIn("inventory_execution_history_current_select", html)
        self.assertIn("inventory_execution_history_rollback_scope", html)
        self.assertIn("inventory_aggregate_update_report_workflow_update_all", html)
        self.assertIn("inventory_aggregate_update_report_workflow_improve_all", html)
        self.assertIn("inventory_aggregate_update_report_atom_summary", html)
        self.assertIn("inventory_aggregate_update_report_title", html)
        self.assertIn("inventory_aggregate_update_report_waiting", html)
        self.assertIn("inventory_aggregate_update_report_empty", html)
        self.assertIn("inventory_aggregate_update_report_summary", html)
        self.assertIn("inventory_aggregate_update_report_prechecks", html)
        self.assertIn("inventory_aggregate_update_report_failures", html)
        self.assertIn("inventory_aggregate_update_report_blocked", html)
        self.assertIn("inventory_aggregate_update_report_managers", html)
        self.assertIn("inventory_aggregate_update_report_cache_hits", html)
        self.assertIn("inventory_aggregate_update_group_meta", html)
        self.assertIn("inventory_aggregate_reason_precheck_failed", html)
        self.assertIn("inventory_aggregate_update_all_precheck_failures", html)
        self.assertIn("inventory_aggregate_update_guidance_manual_managed", html)
        self.assertIn("inventory_aggregate_update_guidance_manual_git", html)
        self.assertIn("/api/skills/aggregates/update-all/history", html)
        self.assertIn("inventory_aggregate_update_guidance_manual_local", html)
        self.assertIn("inventory_aggregate_update_guidance_mixed_sources", html)
        self.assertIn("inventory_aggregate_update_guidance_registry_runtime", html)
        self.assertIn("inventory_aggregate_update_guidance_git_runtime", html)
        self.assertIn("inventory_aggregate_update_guidance_precheck_failed", html)
        self.assertIn("inventory_aggregate_update_guidance_source_sync_failed", html)
        self.assertIn("function inventoryAggregateReasonLabel(", html)
        self.assertIn("function normalizeInventoryExecutionHistoryMode(", html)
        self.assertIn("function syncInventoryExecutionHistoryTabs(", html)
        self.assertIn("function normalizeInventoryAggregateUpdateReport(", html)
        self.assertIn("function normalizeInventoryAggregateUpdateAuditRows(", html)
        self.assertIn("function loadAggregateUpdateAuditTrail(", html)
        self.assertIn("function describeInventoryAggregateUpdateReportView(", html)
        self.assertIn("function describeInventoryCurrentUpdateView(", html)
        self.assertIn("function describeInventoryRollbackAuditView(", html)
        self.assertIn("function renderInventoryExecutionHistoryPanel(", html)
        self.assertIn("function renderInventoryAggregateUpdateReportPanel(", html)
        self.assertIn("inventoryAggregateUpdateReportRows", html)
        self.assertIn("inventoryAggregateUpdateAuditRows", html)
        self.assertIn("/api/skills/aggregates/update-all/history", html)

    def test_inventory_panel_exposes_install_unit_drilldown_panel(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventorySourceInstallUnitBar"', html)
        self.assertIn('id="inventoryInstallUnitsTitle"', html)
        self.assertIn('id="inventoryInstallUnitsNote"', html)
        self.assertIn('id="inventorySourceInstallUnitRows"', html)
        self.assertIn("inventory_install_units_title", html)
        self.assertIn("inventory_install_units_note", html)
        self.assertIn("inventory_install_units_collection", html)
        self.assertIn("inventory_install_units_empty", html)
        self.assertIn("inventorySelectedDetailInstallUnitId", html)
        self.assertIn("data-inventory-install-unit-id", html)

    def test_inventory_panel_exposes_detail_scope_tabs_and_fanout_preview(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventorySourceDetailScopeTabs"', html)
        self.assertIn('id="inventorySourceDetailScopeCollection"', html)
        self.assertIn('id="inventorySourceDetailScopeInstallUnit"', html)
        self.assertIn('id="inventoryFanoutPreviewBar"', html)
        self.assertIn('id="inventoryFanoutPreviewTitle"', html)
        self.assertIn('id="inventoryFanoutPreviewRows"', html)
        self.assertIn("inventory_detail_scope_title", html)
        self.assertIn("inventory_detail_scope_collection", html)
        self.assertIn("inventory_detail_scope_install_unit", html)
        self.assertIn("inventory_fanout_preview_title", html)
        self.assertIn("inventory_fanout_preview_collection", html)
        self.assertIn("inventory_fanout_preview_direct", html)
        self.assertIn("syncInventorySourceDetailScopeTabs()", html)

    def test_inventory_panel_exposes_operation_plan_preview(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryOperationPlanBar"', html)
        self.assertIn('id="inventoryOperationPlanTitle"', html)
        self.assertIn('id="inventoryOperationPlanRows"', html)
        self.assertIn("inventory_operation_plan_title", html)
        self.assertIn("inventory_operation_plan_ready", html)
        self.assertIn("inventory_operation_plan_unsupported", html)
        self.assertIn("inventory_operation_plan_prechecks", html)
        self.assertIn("inventory_operation_plan_precheck_none", html)
        self.assertIn("inventory_operation_plan_blocked_reasons", html)
        self.assertIn("inventory_operation_plan_blocked_reason", html)
        self.assertIn("inventory_operation_plan_blocked_reason_with_code", html)
        self.assertIn("inventory_operation_plan_blocked_reason_with_label", html)
        self.assertIn("inventory_operation_plan_will_execute", html)
        self.assertIn("inventory_operation_plan_will_skip", html)
        self.assertIn('id="inventoryLastUpdateBar"', html)
        self.assertIn('id="inventoryLastUpdateTitle"', html)
        self.assertIn('id="inventoryLastUpdateNote"', html)
        self.assertIn('id="inventoryLastUpdateRows"', html)
        self.assertIn("inventory_last_update_title", html)
        self.assertIn("inventory_last_update_summary", html)
        self.assertIn("inventory_last_update_skipped_groups", html)
        self.assertIn("inventory_last_update_group_summary", html)
        self.assertIn("inventory_last_update_group_item", html)
        self.assertIn("renderInventoryOperationPlan(", html)
        self.assertIn("renderInventoryLastUpdatePanel(", html)

    def test_inventory_panel_exposes_collapsible_source_details_and_compact_skill_details(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventorySourceStructureSummary"', html)
        self.assertIn('id="inventorySourceExecutionSummary"', html)
        self.assertIn("inventory_source_structure_summary", html)
        self.assertIn("inventory_source_execution_summary", html)
        self.assertIn("inventory_target_details_title", html)
        self.assertIn("inventory_skill_more_details", html)
        self.assertIn("inventory-collapsible", html)
        self.assertIn("inventory-skill-extra", html)
        self.assertIn("inventory-skill-primary", html)
        self.assertIn("inventory-skill-secondary", html)
        self.assertRegex(
            html,
            re.compile(r'<details class="inventory-collapsible">\s*<summary id="inventorySourceStructureSummary">', re.S),
        )

    def test_inventory_source_hero_sections_default_to_collapsed_details(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventorySourceHeroSectionOpen: {}", html)
        self.assertIn("function renderInventoryTargetSection(", html)
        self.assertIn('data-inventory-hero-section="${escapeHtml(normalizedKey)}"', html)
        self.assertIn('renderInventoryTargetSection("boundary"', html)
        self.assertIn('renderInventoryTargetSection("members"', html)
        self.assertIn('renderInventoryTargetSection("provenance"', html)
        self.assertIn('renderInventoryTargetSection("mechanism"', html)
        self.assertIn('renderInventoryTargetSection("deploy_notes"', html)
        self.assertIn('$("inventorySourceHero").addEventListener("toggle"', html)


    def test_inventory_panel_exposes_update_plan_support_and_confirmation_hooks(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("getSelectedSourceAggregateUpdatePlan(", html)
        self.assertIn("getSourceAggregateSyncFallbackState(", html)
        self.assertIn("getInventoryOperationPlanMode(", html)
        self.assertIn("inventoryOperationPlanModeLabel(", html)
        self.assertIn("isSourceAggregateUpdateActionable(", html)
        self.assertIn("inventory_operation_plan_mode", html)
        self.assertIn("inventory_operation_plan_mode_source_sync", html)
        self.assertIn("inventory_operation_plan_mode_partial", html)
        self.assertIn("inventory_operation_plan_mode_manual_only", html)
        self.assertIn("actionable", html)
        self.assertIn("inventory_install_unit_update_confirm", html)
        self.assertIn("inventory_install_unit_update_partial_confirm", html)
        self.assertIn("inventory_install_unit_update_unsupported", html)
        self.assertIn("inventory_install_unit_update_source_sync", html)
        self.assertIn("inventory_install_unit_update_skipped", html)
        self.assertIn("actionableUpdatePlan", html)
        self.assertIn("actionableUpdateSupported", html)
        self.assertIn("rememberInventoryLastUpdateForAggregate(", html)
        self.assertIn("getInventoryLastUpdateForAggregate(", html)

    def test_inventory_panel_doctor_summary_reads_aggregate_health(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("install_ready", html)
        self.assertIn("install_missing", html)
        self.assertIn("atom_total", html)
        self.assertIn("atom_resolved", html)
        self.assertIn("atom_partial", html)
        self.assertIn("atom_unresolved", html)
        self.assertIn("provenance_resolved", html)
        self.assertIn("provenance_partial", html)
        self.assertIn("provenance_unresolved", html)
        self.assertIn("group_ready", html)
        self.assertIn("group_missing", html)
        self.assertIn("plan_checked", html)
        self.assertIn("plan_drift", html)
        self.assertIn("doctor.install_atom_health", html)
        self.assertIn("doctor.install_unit_health", html)
        self.assertIn("doctor.install_unit_sync", html)
        self.assertIn("doctor.provenance_health", html)
        self.assertIn("doctor.collection_group_health", html)
        self.assertIn("doctor.collection_group_sync", html)
        self.assertIn("doctor.plan_contract_health", html)

    def test_inventory_panel_exposes_astrbot_runtime_strings_and_slots(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_meta_runtime_backend", html)
        self.assertIn("inventory_meta_host_capabilities", html)
        self.assertIn("inventory_meta_runtime_state", html)
        self.assertIn("inventory_meta_runtime_warnings", html)
        self.assertIn("inventory_astrbot_runtime_title", html)
        self.assertIn("inventory_astrbot_runtime_empty", html)
        self.assertIn("inventory_astrbot_skill_name_label", html)
        self.assertIn("inventory_astrbot_enable", html)
        self.assertIn("inventory_astrbot_disable", html)
        self.assertIn("inventory_astrbot_delete", html)
        self.assertIn("inventory_astrbot_sync_sandbox", html)
        self.assertIn("inventory_astrbot_import_zip", html)
        self.assertIn("inventory_astrbot_export_zip", html)
        self.assertIn("inventory_doctor_astrbot", html)
        self.assertIn('id="inventoryAstrbotRuntimeSummary"', html)
        self.assertIn('id="inventoryAstrbotSkillNameInput"', html)
        self.assertIn('id="inventoryAstrbotEnableBtn"', html)
        self.assertIn('id="inventoryAstrbotDisableBtn"', html)
        self.assertIn('id="inventoryAstrbotDeleteBtn"', html)
        self.assertIn('id="inventoryAstrbotSyncSandboxBtn"', html)
        self.assertIn('id="inventoryAstrbotImportZipBtn"', html)
        self.assertIn('id="inventoryAstrbotExportZipBtn"', html)
        self.assertIn('id="inventoryAstrbotZipInput"', html)
        self.assertIn('id="inventoryAstrbotActionNote"', html)

    def test_inventory_panel_exposes_astrbot_runtime_rendering_helpers(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("function inventoryAstrbotRuntimeSummary(", html)
        self.assertIn("function inventoryAstrbotDoctorSummary(", html)
        self.assertIn("runtime_state_summary", html)
        self.assertIn("runtime_state_warning_count", html)
        self.assertIn("doctor.astrbot_runtime_health", html)
        self.assertIn("function selectedAstrbotHostIdFromHost(", html)
        self.assertIn("function getSelectedAstrbotHostActionContext(", html)
        self.assertIn("async function toggleSelectedAstrbotSkill(", html)
        self.assertIn("async function deleteSelectedAstrbotSkill(", html)
        self.assertIn("async function syncSelectedAstrbotSandbox(", html)
        self.assertIn("async function importSelectedAstrbotSkillZip(", html)
        self.assertIn("async function exportSelectedAstrbotSkillZip(", html)

    def test_inventory_panel_supports_aggregate_selection_rows(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("meaningful_collection_group_rows", html)
        self.assertIn("compatible_meaningful_collection_group_rows_by_software", html)
        self.assertIn("collection_group_rows", html)
        self.assertIn("install_unit_rows", html)
        self.assertIn("data-inventory-source-ids", html)
        self.assertIn("inventorySourceHero", html)
        self.assertIn("/api/skills/install-units/", html)
        self.assertIn("/api/skills/collections/", html)
        self.assertIn('id="inventoryRefreshInstallUnitBtn"', html)
        self.assertIn('id="inventorySyncInstallUnitBtn"', html)
        self.assertIn('id="inventoryUpdateInstallUnitBtn"', html)
        self.assertIn('id="inventoryRollbackInstallUnitBtn"', html)
        self.assertIn('id="inventoryDeployInstallUnitBtn"', html)
        self.assertIn('id="inventoryRepairInstallUnitBtn"', html)
        self.assertIn("refreshSelectedSourceAggregate()", html)
        self.assertIn("syncSelectedSourceAggregate()", html)
        self.assertIn("updateSelectedSourceAggregate()", html)
        self.assertIn("rollbackSelectedSourceAggregate()", html)
        self.assertIn("deploySelectedSourceAggregate()", html)
        self.assertIn("repairSelectedSourceAggregate()", html)
        self.assertIn("/api/skills/install-units/", html)
        self.assertIn("/refresh", html)
        self.assertIn("/repair", html)
        self.assertIn("/sync", html)
        self.assertIn("/update", html)
        self.assertIn("/rollback", html)
        self.assertIn("/deploy", html)

    def test_inventory_panel_exposes_rollback_audit_and_retry_hooks(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryRollbackAuditBar"', html)
        self.assertIn('id="inventoryRollbackAuditTitle"', html)
        self.assertIn('id="inventoryRollbackAuditNote"', html)
        self.assertIn('id="inventoryRollbackAuditRows"', html)
        self.assertIn("inventory_rollback_audit_title", html)
        self.assertIn("inventory_rollback_audit_note_waiting", html)
        self.assertIn("inventory_rollback_audit_note_ready", html)
        self.assertIn("inventory_rollback_audit_note_all", html)
        self.assertIn("inventory_rollback_audit_scope_current", html)
        self.assertIn("inventory_rollback_audit_scope_all", html)
        self.assertIn("inventory_rollback_audit_stats", html)
        self.assertIn("inventory_rollback_audit_failure_groups", html)
        self.assertIn("inventory_rollback_audit_retry_action", html)
        self.assertIn("inventory_rollback_audit_retry_confirm", html)
        self.assertIn("inventory_rollback_audit_retry_success", html)
        self.assertIn("inventory_rollback_audit_retry_error", html)
        self.assertIn("inventory_rollback_audit_focus_action", html)
        self.assertIn("inventory_rollback_audit_focus_error", html)
        self.assertIn("inventory_rollback_audit_event_id", html)
        self.assertIn("inventory_rollback_audit_retry_of", html)
        self.assertIn("inventory_rollback_audit_request_source_manual", html)
        self.assertIn("inventory_rollback_audit_request_source_audit_retry", html)
        self.assertIn("inventory_install_unit_rollback_select_prompt", html)
        self.assertIn("inventory_install_unit_rollback_select_invalid", html)
        self.assertIn("inventory_install_unit_rollback_retry_confirm", html)
        self.assertIn("inventory_install_unit_rollback_retry_success", html)
        self.assertIn("function loadRollbackAuditTrail(", html)
        self.assertIn("function renderInventoryRollbackAuditPanel(", html)
        self.assertIn("function inventoryActionAuditEventId(", html)
        self.assertIn("function withInventoryActionAuditEvent(", html)
        self.assertIn("function inventoryRollbackRetryBeforeRevisions(", html)
        self.assertIn("function inventoryRollbackSuccessMessage(", html)
        self.assertIn("const actionableUpdatePlanInline = getSelectedSourceAggregateUpdatePlan();", html)
        self.assertNotIn("const updateModeLabel = actionableUpdatePlan &&", html)
        self.assertIn("function inventoryRollbackAuditActionEndpoint(", html)
        self.assertIn("async function retryInventoryRollbackAuditRow(", html)
        self.assertIn("async function focusInventorySourceByAggregateId(", html)
        self.assertIn("selectRollbackBeforeRevisions(", html)
        self.assertIn("inventoryRollbackAuditRows", html)
        self.assertIn("inventoryRollbackAuditLoading", html)
        self.assertIn("inventoryRollbackAuditRetrying", html)
        self.assertIn("retry_of_event_id", html)
        self.assertIn("request_source", html)
        self.assertIn("event_id", html)
        self.assertIn("audit_event_id", html)
        self.assertIn("data-inventory-rollback-focus-source-id", html)
        self.assertIn("data-inventory-rollback-retry-row-index", html)
        self.assertIn("/api/skills/audit?limit=120&action=rollback", html)

    def test_inventory_panel_exposes_source_import_wizard_strings_and_hooks(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="inventoryImportSourceBtn"', html)
        self.assertIn('id="inventoryImportModal"', html)
        self.assertIn('id="inventoryImportSourceKind"', html)
        self.assertIn('id="inventoryImportLocatorInput"', html)
        self.assertIn('id="inventoryImportSubpathInput"', html)
        self.assertIn("openInventoryImportModal()", html)
        self.assertIn("submitInventoryImport()", html)
        self.assertIn("inventory_import_open", html)
        self.assertIn("inventory_import_subpath", html)

    def test_inventory_panel_exposes_source_sync_error_labels_and_auth_import_fields(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn("inventory_skill_meta_sync_error", html)
        self.assertIn("inventory_sync_error_repo_metadata_auth_failed", html)
        self.assertIn("inventory_sync_hint_repo_metadata_auth_failed", html)
        self.assertIn("function inventorySyncErrorCodeLabel(", html)
        self.assertIn("function inventorySyncErrorHint(", html)
        self.assertIn('id="inventoryImportSyncApiBaseInput"', html)
        self.assertIn('id="inventoryImportSyncAuthHeaderInput"', html)
        self.assertIn('id="inventoryImportSyncAuthTokenInput"', html)
        self.assertIn("inventory_import_sync_api_base", html)
        self.assertIn("inventory_import_sync_auth_header", html)
        self.assertIn("inventory_import_sync_auth_token", html)

    def test_config_panel_exposes_web_password_mode_controls(self) -> None:
        html = WEBUI_HTML.read_text(encoding="utf-8")

        self.assertIn('id="cfgWebPassword"', html)
        self.assertIn('id="cfgWebPasswordHint"', html)
        self.assertIn('id="cfgWebPasswordClear"', html)
        self.assertIn('id="cfgLabelWebPasswordClear"', html)
        self.assertIn("cfg_web_password_clear", html)
        self.assertIn("cfg_web_password_hint_keep", html)
        self.assertIn("cfg_web_password_hint_set", html)
        self.assertIn("cfg_web_password_hint_clear", html)
        self.assertIn("cfg_web_password_hint_new", html)
        self.assertIn("cfg_web_password_placeholder_configured", html)
        self.assertIn("cfg_web_password_placeholder_empty", html)
        self.assertIn("function syncWebPasswordControls()", html)
        self.assertIn("password_mode", html)
        self.assertIn("cfgWebPasswordClear\").addEventListener(\"change", html)


if __name__ == "__main__":
    unittest.main()
